### ISSUE TITLE
# MVPS:

### ISSUE THREAD

**Issue by TahjDev** [avakil3/Stopify#1]
- [x]  Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of     feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
- [x] MVPs are listed in an ordered list
- [x] Each MVP is broken down into bullet points

**Comment by TahjDev** [comment]
- Can Users also delete playlists? If so can you add that under the playlists MVP

**Comment by avakil3** [comment]
[Comment Addressed]: Yes, users will be able to delete playlists as well. This makes it a CRUD feature since users can create, read, update, and delete playlists.
