### ISSUE TITLE
# Backend Routes

### ISSUE THREAD

**Issue by TahjDev** [avakil3/Stopify#4]
- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in snake_case
- [ ] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
- Ex. probably don't need a GET likes api endpoint because that info comes through the post show

**Comment by TahjDev** [comment]
- So inside of your likes, you shouldn't need them to be nested at all.You can just send the extra information to your backend through the payload with a post request
- And when you delete a like all you'll need is the likes_id
- Can you add an API Endpoints section to differentiate from HTML and Backend

**Comment by avakil3** [comment]
Respond to Bullet #1: That makes sense. I've edited the routes to not nest anymore.
Respond to Bullet #2: Also makes sense. I've edited the route to be `DELETE /api/likes/:likes_id`
Respond to Bullet #3: Sure, I've added that section header.
